// Name: Remote System Discovery - Network
// Description: Checks for execution of MITRE ATT&CK T1018
//
// Severity: Medium
//
// QueryFrequency: 1h
//
// QueryPeriod: 1h
//
// AlertTriggerThreshold: 1
//
// DataSource: #Sysmon
//
// Tactics: #Discovery
//
Sysmon
| where EventID == 1 and (process_command_line contains "net.exe"
and file_directory contains "config")
or (process_command_line contains "ipconfig.exe"
or process_command_line contains "netsh.exe"
or process_command_line contains "arp.exe"
or process_command_line contains "nbtstat.exe")
