// Name: Bypassing Application Whitelisting with Regsvr32
// Description: Checks for execution of MITRE ATT&CK T1117
//
// Severity: High
//
// QueryFrequency: 1h
//
// QueryPeriod: 1h
//
// AlertTriggerThreshold: 1
//
// DataSource: #Sysmon
//
// Tactics: #Defense Evasion
//
Sysmon
| where EventID == 1 and (process_path contains "regsvr32.exe"
or process_path contains "rundll32.exe"
or process_path contains "certutil.exe")
or process_command_line contains "scrobj.dll"