// Name: Application Shimming - FileAccess
// Description: Checks for execution of MITRE ATT&CK T1138
//
// Severity: High
//
// QueryFrequency: 1h
//
// QueryPeriod: 1h
//
// AlertTriggerThreshold: 1
//
// DataSource: #Sysmon
//
// Tactics: #Privilege Escalation, #Persistence
//
Sysmon
| where EventID == 11
and file_name contains "C:\\Windows\\AppPatch\\Custom\\"