// Name: Application Shimming - Registry
// Description: Checks for execution of MITRE ATT&CK T1138
//
// Severity: High
//
// QueryFrequency: 1h
//
// QueryPeriod: 1h
//
// AlertTriggerThreshold: 1
//
// DataSource: #Sysmon
//
// Tactics: #Privilege Escalation, #Persistence
//
Sysmon
| where (EventID == 12 or EventID == 13 or EventID == 14)
and registry_key_path contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\InstalledSDB\\"